-- +goose Up
ALTER TABLE snippets
  ADD COLUMN IF NOT EXISTS draft_cover_image TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_code TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_requires_subscription BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS draft_title_en TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_slug_en TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_excerpt_en TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_category_en TEXT NOT NULL DEFAULT 'Workflow',
  ADD COLUMN IF NOT EXISTS draft_tags_en TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS draft_content_en TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_prompts_en TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_seo_title_en TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_seo_description_en TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_title_zh TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_slug_zh TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_excerpt_zh TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_category_zh TEXT NOT NULL DEFAULT 'Workflow',
  ADD COLUMN IF NOT EXISTS draft_tags_zh TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS draft_content_zh TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_prompts_zh TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_seo_title_zh TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS draft_seo_description_zh TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS has_unpublished_changes BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS draft_updated_at TIMESTAMPTZ NULL;

UPDATE snippets
SET
  draft_cover_image = CASE WHEN draft_cover_image = '' THEN cover_image ELSE draft_cover_image END,
  draft_code = CASE WHEN draft_code = '' THEN code ELSE draft_code END,
  draft_requires_subscription = CASE
    WHEN draft_requires_subscription = FALSE THEN requires_subscription
    ELSE draft_requires_subscription
  END,
  draft_title_en = CASE WHEN draft_title_en = '' THEN title_en ELSE draft_title_en END,
  draft_slug_en = CASE WHEN draft_slug_en = '' THEN slug_en ELSE draft_slug_en END,
  draft_excerpt_en = CASE WHEN draft_excerpt_en = '' THEN excerpt_en ELSE draft_excerpt_en END,
  draft_category_en = CASE WHEN draft_category_en = 'Workflow' AND category_en <> '' THEN category_en ELSE draft_category_en END,
  draft_tags_en = CASE WHEN array_length(draft_tags_en, 1) IS NULL THEN tags_en ELSE draft_tags_en END,
  draft_content_en = CASE WHEN draft_content_en = '' THEN content_en ELSE draft_content_en END,
  draft_prompts_en = CASE WHEN draft_prompts_en = '' THEN prompts_en ELSE draft_prompts_en END,
  draft_seo_title_en = CASE WHEN draft_seo_title_en = '' THEN seo_title_en ELSE draft_seo_title_en END,
  draft_seo_description_en = CASE WHEN draft_seo_description_en = '' THEN seo_description_en ELSE draft_seo_description_en END,
  draft_title_zh = CASE WHEN draft_title_zh = '' THEN title_zh ELSE draft_title_zh END,
  draft_slug_zh = CASE WHEN draft_slug_zh = '' THEN slug_zh ELSE draft_slug_zh END,
  draft_excerpt_zh = CASE WHEN draft_excerpt_zh = '' THEN excerpt_zh ELSE draft_excerpt_zh END,
  draft_category_zh = CASE WHEN draft_category_zh = 'Workflow' AND category_zh <> '' THEN category_zh ELSE draft_category_zh END,
  draft_tags_zh = CASE WHEN array_length(draft_tags_zh, 1) IS NULL THEN tags_zh ELSE draft_tags_zh END,
  draft_content_zh = CASE WHEN draft_content_zh = '' THEN content_zh ELSE draft_content_zh END,
  draft_prompts_zh = CASE WHEN draft_prompts_zh = '' THEN prompts_zh ELSE draft_prompts_zh END,
  draft_seo_title_zh = CASE WHEN draft_seo_title_zh = '' THEN seo_title_zh ELSE draft_seo_title_zh END,
  draft_seo_description_zh = CASE WHEN draft_seo_description_zh = '' THEN seo_description_zh ELSE draft_seo_description_zh END,
  has_unpublished_changes = FALSE,
  draft_updated_at = NULL;

-- +goose Down
ALTER TABLE snippets
  DROP COLUMN IF EXISTS draft_updated_at,
  DROP COLUMN IF EXISTS has_unpublished_changes,
  DROP COLUMN IF EXISTS draft_seo_description_zh,
  DROP COLUMN IF EXISTS draft_seo_title_zh,
  DROP COLUMN IF EXISTS draft_prompts_zh,
  DROP COLUMN IF EXISTS draft_content_zh,
  DROP COLUMN IF EXISTS draft_tags_zh,
  DROP COLUMN IF EXISTS draft_category_zh,
  DROP COLUMN IF EXISTS draft_excerpt_zh,
  DROP COLUMN IF EXISTS draft_slug_zh,
  DROP COLUMN IF EXISTS draft_title_zh,
  DROP COLUMN IF EXISTS draft_seo_description_en,
  DROP COLUMN IF EXISTS draft_seo_title_en,
  DROP COLUMN IF EXISTS draft_prompts_en,
  DROP COLUMN IF EXISTS draft_content_en,
  DROP COLUMN IF EXISTS draft_tags_en,
  DROP COLUMN IF EXISTS draft_category_en,
  DROP COLUMN IF EXISTS draft_excerpt_en,
  DROP COLUMN IF EXISTS draft_slug_en,
  DROP COLUMN IF EXISTS draft_title_en,
  DROP COLUMN IF EXISTS draft_requires_subscription,
  DROP COLUMN IF EXISTS draft_code,
  DROP COLUMN IF EXISTS draft_cover_image;
